### ISSUE TITLE
Filter +1 messages

### ISSUE THREAD

**Issue by onursehitoglu** [kadircet/COWNotifier#21]
+1 messages from hundreds of students are annoying.
A content filter will help a lot.

**Comment by kadircet** [comment]
there's a very naive +1 filtering logic currently [in here](https://github.com/kadircet/COWNotifier/blob/master/newsparser.py#L10). Not sure how well it works for new discourse formatted messages, but it was mostly working with NNTP based cow.

Note that filtering needs to be enabled by sending `/noplus1` to the bot. Please do let us know if it helps. (also for previous messages there should be a flag in the header saying `is_plus_one` if it says True, then the message would've been filtered)
