### ISSUE TITLE
Unable to subscribe two different categories with the same title

### ISSUE THREAD

**Issue by frozsgy** [kadircet/COWNotifier#22]
I just realized that there are 2 "ses" categories, namely "ses" and "social/ses" and it is impossible to subscribe to the regular "ses".  COWNotifier automatically assumes "ses" is "social/ses" (I believe due to lower id)

ses: https://cow.ceng.metu.edu.tr/c/ses/182
social/ses: https://cow.ceng.metu.edu.tr/c/social/ses/35

**Comment by kadircet** [comment]
:( this should be addressed by storing parent names in the leave categories as well. will try to take a look when i've got some time.

in case any one else is interested, modifying the logic in https://github.com/kadircet/COWNotifier/blob/master/newsreader.py#L69 to include parent info in the names should be enough.

**Comment by kadircet** [comment]
Should be fixed with 1b82c0de9618c01894cf0465dab081a17e4ff9a9
